[package]
name = "_10"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
path = "src/main.rs"
name = "10"

[dependencies]
nom = "7.1.3"
rayon = "1.8.0"
